import type { GamerBadge } from "@/components/gamification/badge-grid";

export const mockAchievements: GamerBadge[] = [
  {
    id: 1,
    name: "Explorador Épico",
    description: "Descubre nuevos mundos y amplía tu experiencia gamer.",
    category: "Exploración",
    unlocked: true,
    reward: "+150 XP",
  },
  {
    id: 2,
    name: "Curioso del Catálogo",
    description: "Explora diferentes títulos dentro de ViniGames.",
    category: "Exploración",
    unlocked: true,
    reward: "+50 GameCoins",
  },
  {
    id: 3,
    name: "Cazador de Sombras",
    description: "Completa desafíos competitivos.",
    category: "Competitivo",
    unlocked: false,
    reward: "+200 XP",
  },
  {
    id: 4,
    name: "Dominador de Desafíos",
    description: "Supera múltiples retos competitivos.",
    category: "Competitivo",
    unlocked: false,
    reward: "+250 XP · +50 GameCoins",
  },
  {
    id: 5,
    name: "Coleccionista Puro",
    description: "Amplía tu colección de videojuegos.",
    category: "Colección",
    unlocked: false,
    reward: "+100 GameCoins",
  },
  {
    id: 6,
    name: "Biblioteca de Oro",
    description: "Construye una biblioteca destacada de videojuegos.",
    category: "Colección",
    unlocked: false,
    reward: "+300 XP · +100 GameCoins",
  },
  {
    id: 7,
    name: "Misión Completada",
    description: "Completa una misión especial de ViniGames.",
    category: "Social",
    unlocked: true,
    reward: "+100 XP",
  },
  {
    id: 8,
    name: "Racha Legendaria",
    description: "Mantén una racha de actividad durante 7 días.",
    category: "Social",
    unlocked: false,
    reward: "+50 XP · +50 GameCoins",
  },
  {
    id: 9,
    name: "Crítico de Élite",
    description: "Publica reseñas y participa con la comunidad.",
    category: "Social",
    unlocked: false,
    reward: "+200 XP · +75 GameCoins",
  },
];
