import { CategoryItem, GameItem } from '@/types/catalog';

export const MOCK_CATEGORIES: CategoryItem[] = [
  {
    id: 1,
    name: 'Acción',
    slug: 'accion',
    icon_name: 'Sword',
  },
  {
    id: 2,
    name: 'RPG',
    slug: 'rpg',
    icon_name: 'Shield',
  },
  {
    id: 3,
    name: 'Aventura',
    slug: 'aventura',
    icon_name: 'Compass',
  },
  {
    id: 4,
    name: 'Estrategia',
    slug: 'estrategia',
    icon_name: 'Brain',
  },
  {
    id: 5,
    name: 'Indie',
    slug: 'indie',
    icon_name: 'Sparkles',
  },
  {
    id: 6,
    name: 'Terror',
    slug: 'terror',
    icon_name: 'Ghost',
  },
  {
    id: 7,
    name: 'Carreras',
    slug: 'carreras',
    icon_name: 'Car',
  },
  {
    id: 8,
    name: 'Deportes',
    slug: 'deportes',
    icon_name: 'Trophy',
  },
];

export const MOCK_GAMES: GameItem[] = [
  {
    id: 1,
    title: 'Cyberpunk 2077: Phantom Liberty',
    slug: 'cyberpunk-2077',
    description: 'Sumérgete en Night City como V, un mercenario mejorado cibernéticamente. Vive una aventura de espionaje y suspense en el nuevo distrito de Dogtown con implantes de combate y narrativa ramificada.',
    short_description: 'RPG de acción y mundo abierto ambientado en la megalópolis futurista de Night City.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=8X2kIfS6fb8',
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    release_date: '2023-09-26',
    base_price: 180.0,
    discount_percent: 30,
    final_price: 126.0,
    rating_avg: 4.9,
    rating_count: 680,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 2, name: 'RPG', slug: 'rpg' },
    ],
  },
  {
    id: 2,
    title: 'Elden Ring: Shadow of the Erdtree',
    slug: 'elden-ring',
    description: 'Levántate, Sinluz, y déjate guiar por la gracia para esgrimir el poder del Círculo de Elden y convertirte en el Señor del Círculo en las Tierras Intermedias. Explora la misteriosa Tierra de las Sombras.',
    short_description: 'Aventura de rol y fantasía oscura aclamada mundialmente por FromSoftware.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=qLZenOn7WUo',
    developer: 'FromSoftware Inc.',
    publisher: 'Bandai Namco Entertainment',
    release_date: '2024-06-21',
    base_price: 210.0,
    discount_percent: 20,
    final_price: 168.0,
    rating_avg: 4.95,
    rating_count: 1250,
    age_rating: '16+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 3,
    title: 'Hollow Knight',
    slug: 'hollow-knight',
    description: 'Forja tu propio camino en Hallownest. Una aventura de acción clásica en 2D a través de un vasto mundo interconectado de insectos y héroes. Explora cavernas serpenteantes y lucha contra criaturas corruptas.',
    short_description: 'Aclamado metroidvania 2D de acción y aventura dibujado a mano.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=UAO2urG23S4',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    release_date: '2017-02-24',
    base_price: 55.0,
    discount_percent: 50,
    final_price: 27.5,
    rating_avg: 4.97,
    rating_count: 2400,
    age_rating: '10+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 5, name: 'Indie', slug: 'indie' },
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 4,
    title: 'Red Dead Redemption 2',
    slug: 'red-dead-redemption-2',
    description: 'América, 1899. Arthur Morgan y la banda de Van der Linde se ven obligados a huir. Con agentes federales y los mejores cazarrecompensas pisándoles los talones, deberán atracar, robar y luchar para sobrevivir.',
    short_description: 'La épica historia de forajidos ambientada en los albores del siglo XX.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=eaW0tYpxyp0',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    release_date: '2019-12-05',
    base_price: 200.0,
    discount_percent: 40,
    final_price: 120.0,
    rating_avg: 4.92,
    rating_count: 1890,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 5,
    title: "Baldur's Gate 3",
    slug: 'baldurs-gate-3',
    description: 'Reúne a tu grupo y regresa a los Reinos Olvidados en una historia de compañerismo, traición, sacrificio y la atracción del poder absoluto. Una experiencia RPG de nueva generación basada en D&D.',
    short_description: 'RPG cooperativo de última generación galardonado como Juego del Año.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=1T22wNlUiU8',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    release_date: '2023-08-03',
    base_price: 210.0,
    discount_percent: 15,
    final_price: 178.5,
    rating_avg: 4.98,
    rating_count: 1420,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 4, name: 'Estrategia', slug: 'estrategia' },
    ],
  },
  {
    id: 11,
    title: 'Grand Theft Auto V: Premium Edition',
    slug: 'gta-v',
    description: 'Los Santos: una metrópolis soleada y llena de gurús, aspirantes a estrellas y famosos en decadencia. Tres criminales muy diferentes lo arriesgan todo en una serie de atrevidos y peligrosos golpes.',
    short_description: 'La obra maestra de acción en mundo abierto más vendida de todos los tiempos.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=QkkoHAzjnUs',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    release_date: '2015-04-14',
    base_price: 110.0,
    discount_percent: 35,
    final_price: 71.5,
    rating_avg: 4.85,
    rating_count: 3100,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 12,
    title: 'Black Myth: Wukong',
    slug: 'black-myth-wukong',
    description: 'Black Myth: Wukong es un juego de rol de acción inspirado en la mitología china. Te pondrás en la piel del Predestinado para explorar un reino fascinante y desentrañar una leyenda del pasado.',
    short_description: 'Impresionante RPG de acción basado en la clásica leyenda de Viaje al Oeste.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2358720/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=pnSsgrjpC88',
    developer: 'Game Science',
    publisher: 'Game Science',
    release_date: '2024-08-20',
    base_price: 220.0,
    discount_percent: 10,
    final_price: 198.0,
    rating_avg: 4.91,
    rating_count: 950,
    age_rating: '16+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 13,
    title: 'God of War Ragnarök',
    slug: 'god-of-war-ragnarok',
    description: 'Kratos y Atreus deben viajar a cada uno de los Nueve Reinos en busca de respuestas mientras las fuerzas asgardianas se preparan para la batalla profetizada que acabará con el mundo.',
    short_description: 'La aclamada secuela nórdica con combates viscerales y una historia emotiva.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2322010/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=EE-4G6wh8P4',
    developer: 'Santa Monica Studio',
    publisher: 'PlayStation Publishing LLC',
    release_date: '2024-09-19',
    base_price: 240.0,
    discount_percent: 15,
    final_price: 204.0,
    rating_avg: 4.89,
    rating_count: 780,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 14,
    title: 'Resident Evil 4 Remake',
    slug: 'resident-evil-4',
    description: 'Han pasado 6 años desde el desastre biológico en Raccoon City. El agente Leon S. Kennedy es enviado a rescatar a la hija del presidente en un aislado pueblo europeo donde algo terrible ha sucedido.',
    short_description: 'Reinvención total del clásico juego de terror y acción y supervivencia.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=j5Ic2z3_xp0',
    developer: 'CAPCOM Co., Ltd.',
    publisher: 'CAPCOM Co., Ltd.',
    release_date: '2023-03-24',
    base_price: 170.0,
    discount_percent: 30,
    final_price: 119.0,
    rating_avg: 4.94,
    rating_count: 820,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 6, name: 'Terror', slug: 'terror' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 15,
    title: 'Silent Hill 2 Remake',
    slug: 'silent-hill-2',
    description: 'Tras recibir una carta de su difunta esposa, James se dirige al lugar donde compartieron tantos recuerdos: Silent Hill. Descubre una obra maestra del terror psicológico con gráficos fotorrealistas.',
    short_description: 'El legendario referente del terror psicológico rehecho desde cero con Unreal Engine 5.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2124490/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2124490/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=7hB7UKyF4Hk',
    developer: 'Bloober Team SA',
    publisher: 'KONAMI',
    release_date: '2024-10-08',
    base_price: 230.0,
    discount_percent: 20,
    final_price: 184.0,
    rating_avg: 4.87,
    rating_count: 620,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 6, name: 'Terror', slug: 'terror' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 16,
    title: 'Forza Horizon 5',
    slug: 'forza-horizon-5',
    description: 'Explora los paisajes dinámicos y en constante evolución del mundo abierto de México con una acción de conducción ilimitada y divertida en cientos de los mejores autos del mundo.',
    short_description: 'La experiencia definitiva de carreras en mundo abierto ambientada en México.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1551360/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=FYH9n37B7Yw',
    developer: 'Playground Games',
    publisher: 'Xbox Game Studios',
    release_date: '2021-11-09',
    base_price: 195.0,
    discount_percent: 45,
    final_price: 107.25,
    rating_avg: 4.86,
    rating_count: 1100,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 7, name: 'Carreras', slug: 'carreras' },
      { id: 8, name: 'Deportes', slug: 'deportes' },
    ],
  },
  {
    id: 17,
    title: 'EA SPORTS FC 25',
    slug: 'ea-sports-fc-25',
    description: 'EA SPORTS FC 25 te ofrece más formas de ganar para el club. Forma equipo con tus amigos en tus modos favoritos con 5v5 Rush y lleva a tu club a la victoria con FC IQ.',
    short_description: 'El simulador de fútbol más auténtico y completo del mundo.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2669320/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=pBM2xyCo_Kg',
    developer: 'EA Canada',
    publisher: 'Electronic Arts',
    release_date: '2024-09-27',
    base_price: 250.0,
    discount_percent: 35,
    final_price: 162.5,
    rating_avg: 4.35,
    rating_count: 750,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 8, name: 'Deportes', slug: 'deportes' },
      { id: 7, name: 'Carreras', slug: 'carreras' },
    ],
  },
  {
    id: 18,
    title: 'Hades II',
    slug: 'hades-ii',
    description: 'Enfréntate al Titán del Tiempo en la primera secuela de Supergiant Games. Lanza hechizos con brujería oscura mientras exploras un mundo mítico más profundo.',
    short_description: 'Secuela del galardonado roguelike de acción y mitología griega.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=1F_4Qo0dKFs',
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    release_date: '2024-05-06',
    base_price: 105.0,
    discount_percent: 0,
    final_price: 105.0,
    rating_avg: 4.96,
    rating_count: 890,
    age_rating: '12+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 5, name: 'Indie', slug: 'indie' },
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 2, name: 'RPG', slug: 'rpg' },
    ],
  },
  {
    id: 19,
    title: 'Grand Theft Auto VI',
    slug: 'grand-theft-auto-vi',
    description: 'Grand Theft Auto VI se dirige al estado de Leonida, hogar de las calles bañadas por el neón de Vice City y más allá, en la evolución más grande e inmersiva de la serie.',
    short_description: 'El videojuego más esperado de la historia, ambientado en el estado de Leonida y Vice City.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7d6v.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/054/0545f956cfa1e57c6b90757a3e8abeb0.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=QdBZY2fkU-0',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    release_date: '2026-03-25',
    base_price: 350.0,
    discount_percent: 10,
    final_price: 315.0,
    rating_avg: 4.99,
    rating_count: 4500,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 20,
    title: 'DOOM: The Dark Ages',
    slug: 'doom-the-dark-ages',
    description: 'DOOM: The Dark Ages es la precuela para un jugador de los aclamados DOOM (2016) y DOOM Eternal. Conviértete en el arma definitiva de dioses y reyes en una guerra medieval contra el infierno.',
    short_description: 'Precuela de acción frenética y combate medieval de fantasía oscura.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8ayz.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/025/02580c85c2c78864aa8a9e701968846c.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=4txXm_wZ05I',
    developer: 'id Software',
    publisher: 'Bethesda Softworks',
    release_date: '2025-05-15',
    base_price: 260.0,
    discount_percent: 15,
    final_price: 221.0,
    rating_avg: 4.92,
    rating_count: 430,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 21,
    title: 'The Witcher 3: Wild Hunt',
    slug: 'the-witcher-3',
    description: 'Eres Geralt de Rivia, cazador de monstruos. En un continente devastado por la guerra e infestado de monstruos, tu misión es encontrar a Ciri, la niña de la profecía.',
    short_description: 'Uno de los RPG de mundo abierto más galardonados de la historia.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=XHrskkHf958',
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    release_date: '2015-05-18',
    base_price: 130.0,
    discount_percent: 60,
    final_price: 52.0,
    rating_avg: 4.96,
    rating_count: 2800,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 22,
    title: "Sid Meier's Civilization VI",
    slug: 'civilization-vi',
    description: 'Construye un imperio que resista el paso del tiempo. Explora nuevas tierras, investiga tecnologías, conquista a tus enemigos y enfréntate cara a cara con líderes históricos.',
    short_description: 'El aclamado juego de estrategia por turnos 4X de construcción de civilizaciones.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/289070/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=5KdE0p2joJw',
    developer: 'Firaxis Games',
    publisher: '2K',
    release_date: '2016-10-21',
    base_price: 140.0,
    discount_percent: 70,
    final_price: 42.0,
    rating_avg: 4.81,
    rating_count: 1600,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 4, name: 'Estrategia', slug: 'estrategia' },
    ],
  },
  {
    id: 23,
    title: 'Age of Empires IV: Anniversary Edition',
    slug: 'age-of-empires-iv',
    description: 'Uno de los juegos de estrategia en tiempo real más queridos regresa a la gloria con Age of Empires IV, situándote en el centro de épicas batallas históricas.',
    short_description: 'Estrategia en tiempo real de alta fidelidad con civilizaciones históricas.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1466860/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1466860/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=QflTX_k-5hY',
    developer: 'Relic Entertainment',
    publisher: 'Xbox Game Studios',
    release_date: '2021-10-28',
    base_price: 130.0,
    discount_percent: 33,
    final_price: 87.1,
    rating_avg: 4.8,
    rating_count: 540,
    age_rating: '12+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 4, name: 'Estrategia', slug: 'estrategia' },
    ],
  },
  {
    id: 24,
    title: 'Stardew Valley',
    slug: 'stardew-valley',
    description: 'Has heredado la vieja granja de tu abuelo en Stardew Valley. Equipado con herramientas de segunda mano y unas pocas monedas, te dispones a comenzar tu nueva vida.',
    short_description: 'Encantador simulador de vida y granja RPG con soporte multijugador.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=ot7uXNQskdU',
    developer: 'ConcernedApe',
    publisher: 'ConcernedApe',
    release_date: '2016-02-26',
    base_price: 50.0,
    discount_percent: 20,
    final_price: 40.0,
    rating_avg: 4.98,
    rating_count: 3200,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 5, name: 'Indie', slug: 'indie' },
      { id: 2, name: 'RPG', slug: 'rpg' },
    ],
  },
  {
    id: 25,
    title: 'Monster Hunter Wilds',
    slug: 'monster-hunter-wilds',
    description: 'La fuerza desenfrenada de la naturaleza campa a sus anchas, con entornos que se transforman drásticamente. Caza monstruos colosales con un ecosistema vivo y reactivo.',
    short_description: 'La nueva evolución de la aclamada franquicia de caza de monstruos de Capcom.',
    cover_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2246340/header.jpg',
    banner_image_url: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2246340/capsule_616x353.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=0d8yC1rWc78',
    developer: 'CAPCOM Co., Ltd.',
    publisher: 'CAPCOM Co., Ltd.',
    release_date: '2025-02-28',
    base_price: 260.0,
    discount_percent: 10,
    final_price: 234.0,
    rating_avg: 4.88,
    rating_count: 510,
    age_rating: '16+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 26,
    title: "Marvel's Spider-Man 2",
    slug: 'marvels-spider-man-2',
    description: 'Los Spider-Men Peter Parker y Miles Morales regresan para una nueva y emocionante aventura en la aclamada franquicia. Balancéate por una Nueva York de Marvel ampliada y enfréntate al temible Venom.',
    short_description: 'Aventura de acción superheróica con Peter Parker y Miles Morales.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6m9e.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/0f5/0f50821deec2efb6d3bc8527a20c3ec8.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=9fVYKs4amWo',
    developer: 'Insomniac Games',
    publisher: 'PlayStation Publishing',
    release_date: '2025-01-30',
    base_price: 280.0,
    discount_percent: 15,
    final_price: 238.0,
    rating_avg: 4.93,
    rating_count: 880,
    age_rating: '16+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 27,
    title: 'The Legend of Zelda: Tears of the Kingdom',
    slug: 'zelda-tears-of-the-kingdom',
    description: 'Una épica aventura por la tierra y los cielos de Hyrule te espera en The Legend of Zelda: Tears of the Kingdom. Crea tu propia aventura en un mundo donde el límite es tu imaginación.',
    short_description: 'La obra maestra de mundo abierto y creatividad galardonada de Nintendo Switch.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/5ec/5ecac9fdd3ecd3c62b43b05b07f45f82.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=uHGShqcAHlQ',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    release_date: '2023-05-12',
    base_price: 270.0,
    discount_percent: 10,
    final_price: 243.0,
    rating_avg: 4.98,
    rating_count: 3800,
    age_rating: 'Everyone',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 28,
    title: 'Super Mario Odyssey',
    slug: 'super-mario-odyssey',
    description: 'Acompaña a Mario en una descomunal aventura en 3D por todo el planeta utilizando sus nuevas e increíbles habilidades de captura con Cappy para rescatar a la Princesa Peach.',
    short_description: 'Aclamada aventura de plataformas 3D llena de secretos y diversión.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1m35.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/267/267923fa62cb6394bf32187b8f9e7116.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=wGQHQc_3ycE',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    release_date: '2017-10-27',
    base_price: 230.0,
    discount_percent: 15,
    final_price: 195.5,
    rating_avg: 4.95,
    rating_count: 2900,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 29,
    title: 'Super Smash Bros. Ultimate',
    slug: 'super-smash-bros-ultimate',
    description: '¡Mundos de juegos legendarios y luchadores icónicos colisionan en el enfrentamiento definitivo! Todos los luchadores en la historia de la serie están listos para la batalla.',
    short_description: 'El juego de lucha cruzado más ambicioso y completo de los videojuegos.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ncb.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/89a/89ac9920b721867140e70ad46e8c7518.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=WShCN-AYHqA',
    developer: 'Bandai Namco / Sora Ltd.',
    publisher: 'Nintendo',
    release_date: '2018-12-07',
    base_price: 240.0,
    discount_percent: 20,
    final_price: 192.0,
    rating_avg: 4.96,
    rating_count: 3100,
    age_rating: 'Everyone',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 8, name: 'Deportes', slug: 'deportes' },
    ],
  },
  {
    id: 30,
    title: 'Mario Kart 8 Deluxe',
    slug: 'mario-kart-8-deluxe',
    description: 'Compite con tus amigos en la versión definitiva de Mario Kart 8, con 48 pistas, docenas de personajes, modo batalla renovado y carreras a toda velocidad a 60 FPS.',
    short_description: 'El juego de carreras arcade más vendido y divertido para toda la familia.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1te8.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/0c8/0c8e009a80784be551776136b7ab5f8d.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=tKlRN2YpxRE',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    release_date: '2017-04-28',
    base_price: 220.0,
    discount_percent: 15,
    final_price: 187.0,
    rating_avg: 4.94,
    rating_count: 4200,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 7, name: 'Carreras', slug: 'carreras' },
      { id: 8, name: 'Deportes', slug: 'deportes' },
    ],
  },
  {
    id: 31,
    title: 'Pokémon Escarlata y Púrpura',
    slug: 'pokemon-scarlet-violet',
    description: 'Explora el vasto mundo abierto de la región de Paldea. Descubre nuevos Pokémon, embárcate en tres grandes historias y desata el fenómeno de la Teracristalización.',
    short_description: 'La nueva generación de Pokémon en un vibrante mundo abierto.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4x3s.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/b2d/b2df31c77f0c1e4f4d2f0d9b4b0e9f1a.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=MAmtekgzIag',
    developer: 'Game Freak',
    publisher: 'Nintendo',
    release_date: '2022-11-18',
    base_price: 230.0,
    discount_percent: 10,
    final_price: 207.0,
    rating_avg: 4.60,
    rating_count: 2100,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 32,
    title: 'Metroid Dread',
    slug: 'metroid-dread',
    description: 'Únete a la cazarrecompensas Samus Aran mientras escapa de un letal mundo alienígena plagado por una amenaza mecánica conocida como los robots E.M.M.I.',
    short_description: 'Intensa aventura de acción y exploración en 2D que culmina la saga de Samus.',
    cover_image_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3911.jpg',
    banner_image_url: 'https://media.rawg.io/media/games/740/740e53a7a9cb2ff4497e68fa7cc3b5c6.jpg',
    trailer_url: 'https://www.youtube.com/watch?v=8NjflQn1tK8',
    developer: 'MercurySteam / Nintendo',
    publisher: 'Nintendo',
    release_date: '2021-10-08',
    base_price: 210.0,
    discount_percent: 25,
    final_price: 157.5,
    rating_avg: 4.91,
    rating_count: 1450,
    age_rating: '12+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 5, name: 'Indie', slug: 'indie' },
    ],
  },
];
