import { CategoryItem, GameItem } from '@/types/catalog';

export const MOCK_CATEGORIES: CategoryItem[] = [
  { id: 1, name: 'Acción', slug: 'accion', icon_name: 'Swords' },
  { id: 2, name: 'RPG', slug: 'rpg', icon_name: 'Shield' },
  { id: 3, name: 'Aventura', slug: 'aventura', icon_name: 'Compass' },
  { id: 4, name: 'Indie', slug: 'indie', icon_name: 'Sparkles' },
  { id: 5, name: 'Terror', slug: 'terror', icon_name: 'Ghost' },
  { id: 6, name: 'Estrategia', slug: 'estrategia', icon_name: 'Brain' },
  { id: 7, name: 'Carreras', slug: 'carreras', icon_name: 'Car' },
  { id: 8, name: 'Ciencia Ficción', slug: 'sci-fi', icon_name: 'Rocket' },
];

export const MOCK_GAMES: GameItem[] = [
  {
    id: 1,
    title: 'Neon Odyssey: Cyber Genesis',
    slug: 'neon-odyssey-cyber-genesis',
    description: 'Sumérgete en un futuro distópico dominado por mega-corporaciones e inteligencias artificiales rebeldes. Forja tu propio destino con implantes cibernéticos de combate.',
    short_description: 'Un RPG de acción cyberpunk con combates vertiginosos y narrativa ramificada.',
    cover_image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    banner_image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80',
    trailer_url: 'https://www.youtube.com/watch?v=8X2kIfS6fb8',
    developer: 'ViniStudios',
    publisher: 'ViniGames Publishing',
    release_date: '2026-03-15',
    base_price: 120,
    discount_percent: 25,
    final_price: 90,
    rating_avg: 4.9,
    rating_count: 342,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 8, name: 'Ciencia Ficción', slug: 'sci-fi' },
    ],
  },
  {
    id: 2,
    title: 'Shadows of Eldoria',
    slug: 'shadows-of-eldoria',
    description: 'Explora un vasto reino en ruinas poblado por criaturas míticas y dioses caídos. Domina el arte de la esgrima arcana y desentraña los secretos del Eclipse Eterno.',
    short_description: 'Aventura de fantasía oscura épica con mundo abierto desafiante.',
    cover_image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    banner_image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    trailer_url: null,
    developer: 'Mythic Forge',
    publisher: 'Arcane Interactive',
    release_date: '2025-11-20',
    base_price: 150,
    discount_percent: 15,
    final_price: 127.5,
    rating_avg: 4.8,
    rating_count: 512,
    age_rating: '16+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 3,
    title: 'Hollow Abyss: Remnants',
    slug: 'hollow-abyss-remnants',
    description: 'Un metroidvania 2D dibujado a mano donde descenderás a cavernas olvidadas habitadas por insectos guerreros y vestigios de una civilización perdida.',
    short_description: 'Metroidvania de atmósfera melancólica y combate de precisión.',
    cover_image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    banner_image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1600&q=80',
    trailer_url: null,
    developer: 'Team Velvet',
    publisher: 'Velvet Arts',
    release_date: '2025-08-10',
    base_price: 45,
    discount_percent: 0,
    final_price: 45,
    rating_avg: 4.95,
    rating_count: 1204,
    age_rating: '10+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 4, name: 'Indie', slug: 'indie' },
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 4,
    title: 'Quantum Velocity',
    slug: 'quantum-velocity',
    description: 'Carreras antigravitatorias a velocidades hipersónicas a través de pistas suspendidas sobre megalópolis flotantes con bandas sonoras synthwave.',
    short_description: 'Carreras antigravedad futuristas a más de 1000 km/h.',
    cover_image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'HyperDrive Studio',
    publisher: 'NextGen Motors',
    release_date: '2026-01-28',
    base_price: 70,
    discount_percent: 30,
    final_price: 49,
    rating_avg: 4.4,
    rating_count: 180,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 7, name: 'Carreras', slug: 'carreras' },
      { id: 8, name: 'Ciencia Ficción', slug: 'sci-fi' },
    ],
  },
  {
    id: 5,
    title: 'Echoes of the Asylum',
    slug: 'echoes-of-the-asylum',
    description: 'Survival horror psicológico en primera persona. Explora un hospital psiquiátrico abandonado armado únicamente con una grabadora de audio y baterías limitadas.',
    short_description: 'Terror psicológico inmersivo con sonido binaural aterrador.',
    cover_image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'Nightmare Works',
    publisher: 'Fright Games',
    release_date: '2025-10-31',
    base_price: 60,
    discount_percent: 50,
    final_price: 30,
    rating_avg: 4.6,
    rating_count: 240,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 5, name: 'Terror', slug: 'terror' },
      { id: 3, name: 'Aventura', slug: 'aventura' },
    ],
  },
  {
    id: 6,
    title: 'Galactic Imperium IV',
    slug: 'galactic-imperium-iv',
    description: 'Estrategia espacial 4X a escala cósmica. Gestiona economías planetarias, diplomacia interestelar, árboles tecnológicos y flotas estelares masivas.',
    short_description: 'Estrategia 4X espacial con diplomacia profunda y combate táctico.',
    cover_image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'Stellar Logic',
    publisher: 'Grand Strategy Lab',
    release_date: '2025-06-14',
    base_price: 110,
    discount_percent: 20,
    final_price: 88,
    rating_avg: 4.7,
    rating_count: 670,
    age_rating: '12+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 6, name: 'Estrategia', slug: 'estrategia' },
      { id: 8, name: 'Ciencia Ficción', slug: 'sci-fi' },
    ],
  },
  {
    id: 7,
    title: 'Pixel Dungeons & Dragons',
    slug: 'pixel-dungeons-and-dragons',
    description: 'Roguelike táctico por turnos en pixel art con generación procedural de mazmorras, más de 500 objetos mágicos y muerte permanente opcional.',
    short_description: 'Roguelike táctico por turnos con cientos de combinaciones de hechizos.',
    cover_image_url: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'BitKnight Studios',
    publisher: 'RetroWave Indie',
    release_date: '2025-04-02',
    base_price: 35,
    discount_percent: 0,
    final_price: 35,
    rating_avg: 4.85,
    rating_count: 890,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 4, name: 'Indie', slug: 'indie' },
      { id: 2, name: 'RPG', slug: 'rpg' },
      { id: 6, name: 'Estrategia', slug: 'estrategia' },
    ],
  },
  {
    id: 8,
    title: 'Cyber Ronin: Zero',
    slug: 'cyber-ronin-zero',
    description: 'Conviértete en un samurái cibernético renegado en las calles lluviosas de Neo-Tokio. Domina el parry milimétrico y desata combos con katana de plasma.',
    short_description: 'Hack & slash cyberpunk con combate técnico y estilo visual deslumbrante.',
    cover_image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'KatanaByte',
    publisher: 'ViniGames Publishing',
    release_date: '2026-02-12',
    base_price: 130,
    discount_percent: 35,
    final_price: 84.5,
    rating_avg: 4.75,
    rating_count: 420,
    age_rating: '18+',
    is_featured: true,
    is_active: true,
    categories: [
      { id: 1, name: 'Acción', slug: 'accion' },
      { id: 8, name: 'Ciencia Ficción', slug: 'sci-fi' },
    ],
  },
  {
    id: 9,
    title: 'Forest of Whispers',
    slug: 'forest-of-whispers',
    description: 'Una fábula interactiva sobre la conexión con la naturaleza, puzzles ambientales relajantes y una orquesta en vivo que reacciona a tus pasos.',
    short_description: 'Aventura pacífica y artística de exploración en un bosque ancestral.',
    cover_image_url: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'GreenLeaf Interactive',
    publisher: 'Calm Interactive',
    release_date: '2025-09-18',
    base_price: 40,
    discount_percent: 10,
    final_price: 36,
    rating_avg: 4.65,
    rating_count: 310,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 3, name: 'Aventura', slug: 'aventura' },
      { id: 4, name: 'Indie', slug: 'indie' },
    ],
  },
  {
    id: 10,
    title: 'Bloodmoon Manor',
    slug: 'bloodmoon-manor',
    description: 'Una mansión gótica victoriana infestada de pesadillas sobrenaturales y enigmas ocultistas. Administra tus recursos limitados para sobrevivir la noche.',
    short_description: 'Horror de supervivencia gótico con gestión estricta de inventario.',
    cover_image_url: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'Gothic Soul',
    publisher: 'DarkRealm Entertainment',
    release_date: '2025-12-05',
    base_price: 85,
    discount_percent: 40,
    final_price: 51,
    rating_avg: 4.5,
    rating_count: 195,
    age_rating: '18+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 5, name: 'Terror', slug: 'terror' },
      { id: 1, name: 'Acción', slug: 'accion' },
    ],
  },
  {
    id: 11,
    title: 'Apex Rally 2026',
    slug: 'apex-rally-2026',
    description: 'Simulador definitivo de rally todoterreno con física de neumáticos hiperrealista, clima dinámico en tiempo real y más de 80 etapas internacionales.',
    short_description: 'El simulador de rally más exigente con física y telemetría profesional.',
    cover_image_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'Torque Dynamics',
    publisher: 'Speed Motorsport',
    release_date: '2026-01-10',
    base_price: 140,
    discount_percent: 20,
    final_price: 112,
    rating_avg: 4.8,
    rating_count: 360,
    age_rating: 'Everyone',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 7, name: 'Carreras', slug: 'carreras' },
    ],
  },
  {
    id: 12,
    title: 'Kingdoms of Iron & Magic',
    slug: 'kingdoms-of-iron-and-magic',
    description: 'Construye tu propio imperio medieval fantástico, comanda ejércitos masivos en asedios en tiempo real y forja alianzas en un mapa persistente.',
    short_description: 'Estrategia en tiempo real con asedios épicos y gestión de reinos.',
    cover_image_url: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    banner_image_url: null,
    trailer_url: null,
    developer: 'Crown & Blade Games',
    publisher: 'Iron Gate Global',
    release_date: '2025-07-22',
    base_price: 95,
    discount_percent: 15,
    final_price: 80.75,
    rating_avg: 4.7,
    rating_count: 450,
    age_rating: '12+',
    is_featured: false,
    is_active: true,
    categories: [
      { id: 6, name: 'Estrategia', slug: 'estrategia' },
      { id: 2, name: 'RPG', slug: 'rpg' },
    ],
  },
];
