import { ReviewItem } from '@/types/review.types';

export const MOCK_REVIEWS_BY_GAME: Record<number, ReviewItem[]> = {
  1: [
    {
      id: 101,
      gameId: 1,
      userId: 'user-001',
      rating: 5,
      title: '¡Una obra maestra cyberpunk imperdible!',
      content: 'Muy buena ambientación, el combate es fluido y la banda sonora synthwave te sumerge por completo en la ciudad futurista. Vale cada centavo.',
      isVerifiedPurchase: true,
      helpfulVotesCount: 14,
      unhelpfulVotesCount: 1,
      status: 'APPROVED',
      createdAt: '2026-08-20T14:30:00Z',
      updatedAt: '2026-08-20T14:30:00Z',
      author: {
        id: 'user-001',
        username: 'LunaPlayer',
        avatarUrl: '/avatars/cyber.png',
        currentLevel: 4,
      },
    },
    {
      id: 102,
      gameId: 1,
      userId: 'user-002',
      rating: 5,
      title: 'La historia me sorprendió gratamente',
      content: 'Pensé que sería solo acción, pero la narrativa con decisiones éticas y los giros de guión me dejaron impactado. 100% recomendado.',
      isVerifiedPurchase: true,
      helpfulVotesCount: 9,
      unhelpfulVotesCount: 0,
      status: 'APPROVED',
      createdAt: '2026-08-22T18:15:00Z',
      updatedAt: '2026-08-22T18:15:00Z',
      author: {
        id: 'user-002',
        username: 'PixelEdu',
        avatarUrl: '/avatars/ninja.png',
        currentLevel: 5,
      },
    },
    {
      id: 103,
      gameId: 1,
      userId: 'user-003',
      rating: 4,
      title: 'Gran apartado visual y buen rendimiento',
      content: 'Excelente optimización en PC de gama media. Solo me gustaría que agregaran más misiones secundarias en futuros parches.',
      isVerifiedPurchase: true,
      helpfulVotesCount: 6,
      unhelpfulVotesCount: 2,
      status: 'APPROVED',
      createdAt: '2026-08-23T11:00:00Z',
      updatedAt: '2026-08-23T11:00:00Z',
      author: {
        id: 'user-003',
        username: 'ViniMaster',
        avatarUrl: '/avatars/mech.png',
        currentLevel: 6,
      },
    },
  ],
  2: [
    {
      id: 201,
      gameId: 2,
      userId: 'user-004',
      rating: 5,
      title: 'Velocidad pura y adrenalina',
      content: 'El parkour espacial y la velocidad son increíbles. Los desafíos de tiempo son adictivos.',
      isVerifiedPurchase: true,
      helpfulVotesCount: 8,
      unhelpfulVotesCount: 0,
      status: 'APPROVED',
      createdAt: '2026-08-21T09:20:00Z',
      updatedAt: '2026-08-21T09:20:00Z',
      author: {
        id: 'user-004',
        username: 'AstroRider',
        avatarUrl: '/avatars/cyber.png',
        currentLevel: 3,
      },
    },
  ],
};
